### ISSUE TITLE
Key Event Scancode

### ISSUE THREAD

**Issue by LupusOssorum** [Devisualization/spew#2]
How do I get the Scancode for a key event.  The inclusion of both the scancode (physical key location/name) and the keycode (OS interpreted key i.e. a letter or named key like "shift") is really necessary.  If a user has a remapped keyboard e.g. DVORAK the distinction is real.  

Another reason might be that if the system has a key (e.g. F13) that your code does not know what it is you can still send the scancode to the event handler.  (Yes F13 is a key though most physical keyboards lack this key I can still create it via software. 

Thanks,

**Comment by rikkimax** [comment]
If you need access to the physical key code, something is going wrong. SPEW is trying to get you as far away as possible from this.

The OS handles conversion to Unicode for you. The only place it doesn't count is the special keys like Escape and function and ASCII.

If the system library is converting to Unicode incorrectly then you won't be worrying about SPEW. You won't even get to login :)

**Comment by LupusOssorum** [comment]
True, but, the copy command (ctrl+c with QWERTY keyboards) on programs that are build correctly is not attached to the key that types the  letter "c" but is attached the key that is types "C" on QWERTY but "J" on DVORAK.

You don't need to have a scancode then, but you really do need some way of referencing a key by its location as well as its char (dependent on the keyboard layout) so that a coder using SPEW can use replicate this behavior.

Thankyou,
I don't mean to sound rude.

**Comment by rikkimax** [comment]
I do not support accelerator keys.

https://stackoverflow.com/questions/22842638/dvorak-typers-how-do-you-handle-shortcuts-like-ctrl-c

Short answer is, that it isn't my problem :)

You're not rude, quite polite actually.

**Comment by LupusOssorum** [comment]
Okay.

With a char, how do you distinguish between the numpad and the number row?  Doing so can be very important in games.

**Comment by rikkimax** [comment]
I don't currently.

But I suppose adding a modifier to signal that a key originates from the keypad wouldn't be a terrible idea.

**Comment by LupusOssorum** [comment]
Okay, you can ditch the Scancode, I liked the power it gave to a user that might want to use it.

I think one thing your system currently misses is the ability to identify and test every key with a single variable.  This makes customize-able keys in games easier.

I first learned Python and Pygame and still like what they did. ("https://www.pygame.org/docs/ref/event.html")

Pygames KeyEvent had three attributes 
`unicode`    is the equivalent to your "dchar"
`key`    is the unique identifier for every key (an Enum but not just for special keys)
`mod`    the modifiers.

I think this gives much more power and ease of use.


If you need to test for a random key use:
key == Keys.upArrow
key == Key.A // Works (though you may not recommend it) is not case sensitive without going out of the way to call a lower or do an `||`.
key == Key.Numpad_5

Or if you want to do typing
string += unicode
if (key == Keys.backspace) { string = string[0..$-1] }


I much prefer this, and it allows the user of the code to do it how he wants.  (Also simple and easy to understand; I know understood it and I was ~10).

**Comment by rikkimax** [comment]
Something in that post smells of bad code.

I really really do not wish to support (something like) uint.max*4 combination of graphical characters in a single enum.

Unicode has multiple levels and I'm not talking about the codepoint size (UTF-8 versus UTF-32). Code points get combined and evaluated into different graphical characters all together. There are some that deal solely in direction of text.

Let's stick with codepoints, and not introduce things just for the sake convenience and create problems.
And at any rate

```D
import std.uni : toLower;
if (key.toLower == 'a') {
    ...
}
```

Seems easy enough to me.

**Comment by LupusOssorum** [comment]
Um, I didn't think about that fact that all Unicode char events are possible.

I think either most of those Unicode characters (due to not being having physical keys) would be left as `Unknown` or just a `uint` value that is not named in the `enum`.

Pygame does it, so it is not undone, and Pygame is very popular rather powerful and very easy for noobs, but I get that only says so much.

`key.toLower` is a rather unnecessary calculation (albeit small), if we want to code with a low-level compiled language I think speed is something to take into consideration (many users of the library will be looking for it).

I can see how you wouldn't want a `uint.max*4` long `enum`... but I don't see how it smells of bad code, despite a lot of repetitive code, it is rather obvious repetition (you could also use a D `mixin` probably) and thus is not error/mistake prone.

Lastly, the biggest thing I like about D is the vision to allow the coder to code the way **he** wants and not to force a way on him.  And continuing that same vision, I think a fuller `key` would give the coder the ability to do it how he wants.

Thanks for hearing my opinion, I appreciate it.

**Comment by rikkimax** [comment]
Ahh I see the misunderstanding here, Pygame isn't equivalent to SPEW, it is equivalent to Dgame.

SPEW is a windowing library, it is all about abstracting away system implementation details so you more or less have a consistent experience cross platform, this alone is very hard to do.

If you want convenience, you don't want to be talking to SPEW directly. I try to make as few assumptions as possible. Higher level wrapper libraries and frameworks which you are use to, do this. But a good base means a better experience over all.

**Comment by rikkimax** [comment]
As it turns out, when I went to go implement a Numpad modifier I discovered I was a bit smarter than I originally thought. I just called it Numlock instead.

**Comment by LupusOssorum** [comment]
If you want to leave out convenience why have the "unicode" thing at all?  That to me seams like a higher level thing.

No I am not looking for convenience, I am looking for a low level cross system wrapper that does not force a way of use.  Using a simple identifier for each key is a direct way of dealing with keyboard.  Using a Unicode interpretation of the key breaks distinctions between keys that require funny flags to distinguish.  The `unicode`/`char` value is infact an interpretation of Keyboard events as it gives the char outcome of the key and not the fact that a particular key is pressed.  If a keyboard were only ever used for typing characters this extrapolation would be great but keys are used for other events as well.  

You are in this portion of code
```switch (code) {
		case VK_NUMPAD0: .. case VK_NUMPAD9:
			key = cast(dchar)('0' + (code - VK_NUMPAD0));
			modifiers |= KeyModifiers.Numlock; break;
		case 'A': .. case 'Z':
			key = cast(dchar)(isCapital ? code : (code + Atoa));
			break;
		. . .
		case VK_OEM_1:
			key = isShift ? ':' : ';'; break;
		case VK_OEM_2:
			key = isShift ? '?' : '/'; break;
		case VK_OEM_PLUS:
			key = isShift ? '+' : '='; break;
		case VK_OEM_MINUS:
			key = isShift ? '_' : '-'; break;
		case VK_OEM_COMMA:
			key = isShift ? '<' : ','; break;
		case VK_OEM_PERIOD:
			key = isShift ? '>' : '.'; break;
		case VK_OEM_7:
			key = isShift ? '"' : '\''; break;
		case VK_OEM_5:
			key = isShift ? '|' : '\\'; break;
```
you are doing extra operations to convert to a char.  Though on mobile these destinations may not exist.  Even Pygame a high level Game Engine library gives a lower level view of the data that the OS is giving, by a KeyCode along with a Unicode.

By doing this "interpretation" of the Keyboard event you cause calculations and either must be undone for a coder the get the data he really wants (e.g. what key actually got pressed) or disallow the ability to get the specifics he needs.

To get the the actual key that was pressed without causing any other key do have the same action or ignoring modifiers like shift or ctrl (Very necessary in games) you would have to do something like this.
```
window.windowEvents.onKeyPress = (dchar key, SpecialKey specialKey, ushort modifiers) {
		if (key.lower==userSetting.key && specialKey==userSetting.specialKey && modifies&NumLock) {
                     //Key was pressed
                }
	};
```  
This should work but also **assumes things that are never guaranteed** to be true (And when using a lowlevel library to have to undo an operation by the library seems wrong!).  What if two keys on some strange keyboard/layout cause the same char but neither is on the numpad.
By simply having `SpecialKey` be a complete `KeyIdentifier` you could do
```
if (specialId==userSetting) {
         //Key was pressed
}
```

Thanks again for reading **ALL** that...

**Comment by LupusOssorum** [comment]
By the way the reason I am so stubborn on this.  I like this library in most aspects and intend to use it and make other libraries that interface with it as well as contribute to this library directly.  I am quite happy to make wrappers to change the interface for a library for myself but to wrap the interface you have I would have to have a very quirky operations like I showed above.  And just recodeing that potion of the library would be excessively difficult.

**Comment by rikkimax** [comment]
Unicode is provided by the system library, not me, I just call into it to set it.

https://github.com/Devisualization/spew/blob/master/src/base/cf/spew/event_loop/wells/winapi.d#L545
Notice the cast to dchar there?

You won't get me to change, this isn't my first [design](https://github.com/rikkimax/DOOGLE/blob/master/source/WindowManagement/doogle/events/types.d#L9) and I have done it more or less the way you're thinking of it.

I live in the system library level, you're living a couple of layers above that. If I muck up the kernel can panic and end with a BSOD. When you muck up, your program crashes or it displays the wrong color.

I won't be changing this part of the API.
Implement a platform (X11 please, I have requests for this) and then we can discuss it.
Until then your viewpoint is clouded with not understanding what the code is doing or how it originated.

**Comment by LupusOssorum** [comment]
Okay, thanks for hearing what I had to say.
