### ISSUE TITLE
linux timers without libuv

### ISSUE THREAD

**Issue by ghost** [Devisualization/spew#40]
Current plan shows that under GNU/Linux libUV will be mandatory for timers.
I'm sure there should be a way using x11

```diff
- - [x] Timer
+ - [ ] Timer
    - [x] WinAPI
    - [x] LibUV
+    - [ ] X11
```

**Comment by rikkimax** [comment]
X11 does not provide timers, nor does the Linux kernel.

There is no way to do what you want without implementing it manually like LibUV is already doing for me.

**Comment by ghost** [comment]
i think that's a bit a concern to pull-in libuv just for this, the other parts of SPEW for linux can work without (e.g i imagine usage in kheops)

**Comment by rikkimax** [comment]
SPEW also supports high performance sockets via LibUV, so it kills 2 birds with one stone territory.

It's important to make sockets and windowing work well together. You could get some very interesting locking up otherwise ;)
